spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:clm}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}.1syajun.mongodb.net/?retryWrites=true&w=majority

clm:
  jwt:
    secret-key: 711a92992d40a1cc0bf64ab3837050ef3dfc26aa42a9623383e67ba72ba788dd
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}
    refresh-token-historical: ${JWT_REFRESH_TOKEN_HISTORICAL:2592000000}
    cookie-name: ${JWT_COOKIE_NAME:clm-cookie}
# email:
#   host: ${EMAIL_HOST:smtp.gmail.com}
#   tsl-port: ${EMAIL_PORT:587}
#   ssl-port: ${EMAIL_SSL_PORT:465}
#   account: ${EMAIL_IDENTIFIER:champsmanagement03@gmail.com}
#   password: ${EMAIL_PASSWORD:zkmoezwkdursnxmg}

# mail:
#   smtp:
#     auth: true,
#     host: smtp.gmail.com
#     starttls:
#       enable: true
#       required: true
#     port: 587
