spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:clm}
      uri: mongodb+srv://${MONGO_USER:admin}:${MONGO_PASSWORD:admin}@${MONGO_CLUSTER:clm}.1syajun.mongodb.net/?retryWrites=true&w=majority

clm:
  upload:
    path:
      image: ${CLM_UPLOAD_PATH_IMAGE:client_upload/images}
      document: ${CLM_UPLOAD_PATH_DOCUMENT:client_upload/documents}
    max-size: ${CLM_UPLOAD_MAX_SIZE:5MB}
    max-request-size: ${CLM_UPLOAD_MAX_REQUEST_SIZE:5MB}
    file-size-threshold: ${CLM_UPLOAD_FILE_SIZE_THRESHOLD:0}
  url: ${CLM_URL:http://localhost:8080}
  client:
    base:
      url: ${CLM_CLIENT_URL:http://localhost:3000}
      endpoint:
        login: ${CLM_CLIENT_LOGIN_ENDPOINT:/login}
        error: ${CLM_CLIENT_ERROR_ENDPOINT:/error}

  api:
    url:
      v1: ${CLM_API_V1_URL:http://localhost:8080/v1}

  jwt:
    secret-key: 711a92992d40a1cc0bf64ab3837050ef3dfc26aa42a9623383e67ba72ba788dd
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}
    refresh-token-historical: ${JWT_REFRESH_TOKEN_HISTORICAL:2592000000}
    cookie-name: ${JWT_COOKIE_NAME:clm-cookie}
  props:
    max-team-template: 3

email:
  host: ${EMAIL_HOST:smtp.gmail.com}
  port: ${EMAIL_PORT:587}
  username: ${EMAIL_USERNAME:champsmanagement03@gmail.com}
  password: ${EMAIL_PASSWORD:keongqikngzilclv}
  verification-expiration: ${EMAIL_VERIFICATION_EXPIRATION:86400000}
